// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates restock alerts for products based on inventory levels.
 *
 * - generateRestockAlert - A function that generates a restock alert for a product.
 * - RestockAlertInput - The input type for the generateRestockAlert function.
 * - RestockAlertOutput - The return type for the generateRestockAlert function.
 */

import {ai} from '@/ai/genkit';
import {googleAI} from '@genkit-ai/googleai';
import {z} from 'genkit';

const RestockAlertInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  vendorName: z.string().describe('The name of the vendor.'),
  currentInventory: z.number().describe('The current inventory level of the product.'),
  restockThreshold: z.number().describe('The minimum inventory level before a restock is needed.'),
});
export type RestockAlertInput = z.infer<typeof RestockAlertInputSchema>;

const RestockAlertOutputSchema = z.object({
  alertMessage: z.string().describe('The generated restock alert message.'),
  restockNeeded: z.boolean().describe('Whether a restock is needed or not.'),
});
export type RestockAlertOutput = z.infer<typeof RestockAlertOutputSchema>;

export async function generateRestockAlert(input: RestockAlertInput): Promise<RestockAlertOutput> {
  return restockAlertFlow(input);
}

const prompt = ai.definePrompt({
  name: 'restockAlertPrompt',
  model: googleAI.model('gemini-1.5-pro'),
  input: {schema: RestockAlertInputSchema},
  output: {schema: RestockAlertOutputSchema},
  prompt: `You are an inventory management assistant. Your task is to generate restock alerts for products when their inventory level falls below a predefined threshold.

Product Name: {{{productName}}}
Vendor Name: {{{vendorName}}}
Current Inventory: {{{currentInventory}}}
Restock Threshold: {{{restockThreshold}}}

Determine if a restock is needed based on whether the current inventory is below the restock threshold. Then, generate a concise and informative alert message that includes the product name, vendor name, current inventory, and restock threshold. Set the restockNeeded field to true if a restock is needed, and false otherwise.
`,
});

const restockAlertFlow = ai.defineFlow(
  {
    name: 'restockAlertFlow',
    inputSchema: RestockAlertInputSchema,
    outputSchema: RestockAlertOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
