// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Monitors product stock levels against sales velocity to predict potential shortages.
 *
 * - checkStockAvailability - A function that checks if a product's available stock is sufficient based on its recent sales.
 * - StockAvailabilityInput - The input type for the checkStockAvailability function.
 * - StockAvailabilityOutput - The return type for the checkStockAvailability function.
 */

import {ai, googleAI} from '@/ai/genkit';
import {z} from 'genkit';

const StockAvailabilityInputSchema = z.object({
  productName: z.string().describe('The name of the product or variant.'),
  physicalStock: z.number().describe('The total physical stock count.'),
  reservedStock: z.number().describe('The total reserved stock count.'),
  salesLast7Days: z.number().describe('Total units sold in the last 7 days.'),
});
export type StockAvailabilityInput = z.infer<typeof StockAvailabilityInputSchema>;

const StockAvailabilityOutputSchema = z.object({
  alertTriggered: z
    .boolean()
    .describe(
      'Whether the available stock is critically low based on sales velocity.'
    ),
  alertMessage: z
    .string()
    .describe('A human-readable message explaining the stock status.'),
  dailyAverageSales: z.number().describe('The calculated average daily sales.'),
  availableForSale: z.number().describe('The calculated stock available for sale (physical - reserved).'),
});
export type StockAvailabilityOutput = z.infer<
  typeof StockAvailabilityOutputSchema
>;

export async function checkStockAvailability(
  input: StockAvailabilityInput
): Promise<StockAvailabilityOutput> {
  return stockAvailabilityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'stockAvailabilityPrompt',
  model: googleAI.model('gemini-1.5-pro'),
  input: {schema: StockAvailabilityInputSchema},
  output: {schema: StockAvailabilityOutputSchema},
  prompt: `You are an expert inventory analyst. Your task is to determine if a product is at risk of running out of stock available for new reservations.

Calculate the stock available for sale by subtracting reserved stock from physical stock.
Calculate the average daily sales based on the sales from the last 7 days.

The alert condition is triggered if the stock available for sale is less than the average daily sales multiplied by 3 (our safety buffer).

Analyze the following data:
- Product Name: {{{productName}}}
- Physical Stock: {{{physicalStock}}}
- Reserved Stock: {{{reservedStock}}}
- Sales in the last 7 days: {{{salesLast7Days}}}

Based on your analysis, set the 'alertTriggered' field to true or false.
Then, generate a concise 'alertMessage' that summarizes the situation. For example: "OK: Stock disponible (25) es suficiente para la venta diaria promedio (2.1).", or "Alerta: Stock disponible (5) es bajo comparado con la venta diaria promedio (4.3)."
Finally, fill in the 'dailyAverageSales' and 'availableForSale' fields with your calculated values.`,
});

const stockAvailabilityFlow = ai.defineFlow(
  {
    name: 'stockAvailabilityFlow',
    inputSchema: StockAvailabilityInputSchema,
    outputSchema: StockAvailabilityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
