// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore, initializeFirestore, persistentLocalCache, persistentMultipleTabManager } from "firebase/firestore";

export const firebaseConfig = {
  apiKey: "AIzaSyAFrZ4jvO5fIF9koe0cMUUwO1r_b5fdBRk",
  authDomain: "studio-9748962172-82b35.firebaseapp.com",
  databaseURL: "https://studio-9748962172-82b35-default-rtdb.firebaseio.com",
  projectId: "studio-9748962172-82b35",
  storageBucket: "studio-9748962172-82b35.firebasestorage.app",
  messagingSenderId: "607501701912",
  appId: "1:607501701912:web:753a676ca0723828e4c46d"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

// Initialize Firestore with persistence
let db;
try {
  db = initializeFirestore(app, {
    localCache: persistentLocalCache({
      tabManager: persistentMultipleTabManager()
    })
  });
} catch (e) {
  // If already initialized, get the existing instance
  db = getFirestore(app);
}

export { app, db };
