// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore, enableIndexedDbPersistence, CACHE_SIZE_UNLIMITED } from "firebase/firestore";

export const firebaseConfig = {
  apiKey: "AIzaSyAFrZ4jvO5fIF9koe0cMUUwO1r_b5fdBRk",
  authDomain: "studio-9748962172-82b35.firebaseapp.com",
  databaseURL: "https://studio-9748962172-82b35-default-rtdb.firebaseio.com",
  projectId: "studio-9748962172-82b35",
  storageBucket: "studio-9748962172-82b35.firebasestorage.app",
  messagingSenderId: "607501701912",
  appId: "1:607501701912:web:753a676ca0723828e4c46d"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

// Initialize Firestore WITHOUT persistence to prevent connection issues
// Persistence was causing "Connection closed" errors on Firebase App Hosting
const db = getFirestore(app);

// Enable offline persistence
if (typeof window !== 'undefined') {
  enableIndexedDbPersistence(db, {
    cacheSizeBytes: CACHE_SIZE_UNLIMITED
  }).catch((err) => {
    if (err.code === 'failed-precondition') {
      // Multiple tabs open, persistence can only be enabled in one tab at a time
      console.warn('Firebase persistence failed: Multiple tabs open');
    } else if (err.code === 'unimplemented') {
      // The current browser does not support all features
      console.warn('Firebase persistence not supported in this browser');
    }
  });
}

export { app, db };
