// This is an autogenerated file from Firebase Studio.
"use server";

import { getOrGenerateStockAlerts } from "@/lib/api";
import { revalidatePath } from "next/cache";

export async function regenerateStockAlertsAction() {
    try {
        await getOrGenerateStockAlerts(true); // Force regeneration
        revalidatePath('/stock-alerts');
        return { success: true, message: "Alertas de stock regeneradas exitosamente." };
    } catch (error) {
        console.error("Error regenerating stock alerts:", error);
        return { success: false, message: "No se pudieron regenerar las alertas de stock." };
    }
}
