// This is an autogenerated file from Firebase Studio.
"use server";

import { generateAndCacheStockAlerts } from "@/lib/api";
import { revalidatePath } from "next/cache";

export async function regenerateStockAlertsAction() {
    try {
        await generateAndCacheStockAlerts();
        revalidatePath('/stock-alerts');
        return { success: true, message: "Alertas de stock regeneradas exitosamente." };
    } catch (error) {
        console.error("Error regenerating stock alerts:", error);
        const errorMessage = error instanceof Error ? error.message : "No se pudieron regenerar las alertas de stock.";
        return { success: false, message: errorMessage };
    }
}
